# set `baseurl` to your root domain
# if you set it to "/" share icons won't work properly on production
# baseurl = "https://dzwriters.com/"  # Include trailing slash

copyright = "Copyright © 2022, DzWriters community all rights reserved."
# canonifyurls = true
paginate = 10
theme = "hugo-clarity"
disqusShortname = ""
DefaultContentLanguage = "ar"

[languages]
[languages.ar]
  contentDir = 'content/arabic'
  languagedirection = 'rtl'
  LanguageName = "العربية"
  title = 'DzWriters'
  weight = 1
  description = ""
  introDescription = "**مجتمع DzWriters** هو المكان المثالي للجزائريين لمشاركة معارفهم وخبراتهم مع الآخرين. من خلال نهج تشاركي ، يمكن للجميع الاستفادة من ثروة المعلومات والخبرات المتاحة داخل المجتمع."
[languages.en]
  contentDir = 'content/english'
  title = "DzWriters"
  LanguageName = "English"
  weight = 2
  description = ""
  introDescription = "The **DzWriters community** is the perfect place for Algerians to share their knowledge and experience with others. With a participatory approach, everyone can benefit from the wealth of information and expertise available within the community."
[languages.fr]
  contentDir = 'content/french'
  title = "DzWriters"
  LanguageName = "Français"
  weight = 3
  description = ""
  introDescription = "La **communauté DzWriters** est l'endroit idéal pour que les Algériens partagent leurs connaissances et leur expérience avec les autres. Grâce à une approche participative, chacun peut bénéficier de la richesse des informations et des expériences disponibles au sein de la communauté."



#[menus]
#config/_default/menus/menu.ar.toml


[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
customCSS = ["css/custom.css"] # Include custom CSS files
customJS = ["js/custom.js"] # Include custom JS files