
[ar]
  contentDir = 'content/arabic'
  languagedirection = 'rtl'
  title = 'DzWriters - الكتاب الجزائريون'
  weight = 1
[en]
  contentDir = 'content/english'
  title = "DzWriters - Algerian writers"
  LanguageName = "English"
  weight = 2

[fr]
  contentDir = 'content/french'
  title = "DzWriters - Écrivains algériens"
  LanguageName = "Français"
  weight = 3
